services:

  mysql:
    image: mysql:8.0
    container_name: smart-canteen-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} --silent"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - fullstack-net


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: smart-canteen-backend
    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    volumes:
      - menu_images:/app/uploads

    networks:
      - fullstack-net


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: smart-canteen-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5173:80"

    networks:
      - fullstack-net


volumes:
  mysql_data:
  menu_images:


networks:
  fullstack-net:
    driver: bridge


